2024-01-19T05:06:17.612170+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-01-19T05:06:17.612170+00:00 app[web.1]: return util.import_app(self.app_uri)
2024-01-19T05:06:17.612170+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.612171+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
2024-01-19T05:06:17.612171+00:00 app[web.1]: mod = importlib.import_module(module)
2024-01-19T05:06:17.612171+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.612174+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-01-19T05:06:17.612175+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2024-01-19T05:06:17.612176+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.612176+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-01-19T05:06:17.612176+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-01-19T05:06:17.612176+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-01-19T05:06:17.612176+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-01-19T05:06:17.612177+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 994, in exec_module
2024-01-19T05:06:17.612177+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-01-19T05:06:17.612177+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2024-01-19T05:06:17.612177+00:00 app[web.1]: from affirmative_app import app##, db  # Assuming your package is named affirmative_app
2024-01-19T05:06:17.612177+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.612178+00:00 app[web.1]: File "/app/affirmative_app/__init__.py", line 3, in <module>
2024-01-19T05:06:17.612178+00:00 app[web.1]: from .config import *
2024-01-19T05:06:17.612178+00:00 app[web.1]: ModuleNotFoundError: No module named 'affirmative_app.config'
2024-01-19T05:06:17.612238+00:00 app[web.1]: [2024-01-19 05:06:17 +0000] [8] [INFO] Worker exiting (pid: 8)
2024-01-19T05:06:17.613051+00:00 app[web.1]: [2024-01-19 05:06:17 +0000] [7] [ERROR] Exception in worker process
2024-01-19T05:06:17.613051+00:00 app[web.1]: Traceback (most recent call last):
2024-01-19T05:06:17.613051+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2024-01-19T05:06:17.613051+00:00 app[web.1]: worker.init_process()
2024-01-19T05:06:17.613051+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-01-19T05:06:17.613051+00:00 app[web.1]: self.load_wsgi()
2024-01-19T05:06:17.613052+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-01-19T05:06:17.613052+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2024-01-19T05:06:17.613052+00:00 app[web.1]: ^^^^^^^^^^^^^^^
2024-01-19T05:06:17.613052+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-01-19T05:06:17.613052+00:00 app[web.1]: self.callable = self.load()
2024-01-19T05:06:17.613052+00:00 app[web.1]: ^^^^^^^^^^^
2024-01-19T05:06:17.613052+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-01-19T05:06:17.613053+00:00 app[web.1]: return self.load_wsgiapp()
2024-01-19T05:06:17.613053+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.613053+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-01-19T05:06:17.613053+00:00 app[web.1]: return util.import_app(self.app_uri)
2024-01-19T05:06:17.613053+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.613053+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
2024-01-19T05:06:17.613054+00:00 app[web.1]: mod = importlib.import_module(module)
2024-01-19T05:06:17.613054+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.613054+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-01-19T05:06:17.613054+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2024-01-19T05:06:17.613054+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.613054+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-01-19T05:06:17.613055+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-01-19T05:06:17.613055+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-01-19T05:06:17.613055+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-01-19T05:06:17.613055+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 994, in exec_module
2024-01-19T05:06:17.613056+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-01-19T05:06:17.613056+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2024-01-19T05:06:17.613056+00:00 app[web.1]: from affirmative_app import app##, db  # Assuming your package is named affirmative_app
2024-01-19T05:06:17.613056+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.613056+00:00 app[web.1]: File "/app/affirmative_app/__init__.py", line 3, in <module>
2024-01-19T05:06:17.613057+00:00 app[web.1]: from .config import *
2024-01-19T05:06:17.613057+00:00 app[web.1]: ModuleNotFoundError: No module named 'affirmative_app.config'
2024-01-19T05:06:17.613210+00:00 app[web.1]: [2024-01-19 05:06:17 +0000] [7] [INFO] Worker exiting (pid: 7)
2024-01-19T05:06:17.685708+00:00 app[web.1]: [2024-01-19 05:06:17 +0000] [2] [ERROR] Worker (pid:8) exited with code 3
2024-01-19T05:06:17.687215+00:00 app[web.1]: [2024-01-19 05:06:17 +0000] [2] [ERROR] Worker (pid:7) exited with code 3
2024-01-19T05:06:17.687251+00:00 app[web.1]: Traceback (most recent call last):
2024-01-19T05:06:17.687261+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 209, in run
2024-01-19T05:06:17.687470+00:00 app[web.1]: self.sleep()
2024-01-19T05:06:17.687506+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 360, in sleep
2024-01-19T05:06:17.687598+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2024-01-19T05:06:17.687793+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-19T05:06:17.687818+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-01-19T05:06:17.687873+00:00 app[web.1]: self.reap_workers()
2024-01-19T05:06:17.687894+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
2024-01-19T05:06:17.687982+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-01-19T05:06:17.688025+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2024-01-19T05:06:17.688037+00:00 app[web.1]: 
2024-01-19T05:06:17.688038+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2024-01-19T05:06:17.688041+00:00 app[web.1]: 
2024-01-19T05:06:17.688051+00:00 app[web.1]: Traceback (most recent call last):
2024-01-19T05:06:17.688060+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2024-01-19T05:06:17.688099+00:00 app[web.1]: sys.exit(run())
2024-01-19T05:06:17.688168+00:00 app[web.1]: ^^^^^
2024-01-19T05:06:17.688180+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2024-01-19T05:06:17.688232+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2024-01-19T05:06:17.688255+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 236, in run
2024-01-19T05:06:17.688332+00:00 app[web.1]: super().run()
2024-01-19T05:06:17.688345+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 72, in run
2024-01-19T05:06:17.688410+00:00 app[web.1]: Arbiter(self).run()
2024-01-19T05:06:17.688431+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 229, in run
2024-01-19T05:06:17.688506+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2024-01-19T05:06:17.688528+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 342, in halt
2024-01-19T05:06:17.688601+00:00 app[web.1]: self.stop()
2024-01-19T05:06:17.688642+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 396, in stop
2024-01-19T05:06:17.688697+00:00 app[web.1]: time.sleep(0.1)
2024-01-19T05:06:17.688717+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-01-19T05:06:17.688773+00:00 app[web.1]: self.reap_workers()
2024-01-19T05:06:17.688791+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
2024-01-19T05:06:17.688881+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-01-19T05:06:17.688918+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2024-01-19T05:06:17.761439+00:00 heroku[web.1]: Process exited with status 1
2024-01-19T05:06:17.782936+00:00 heroku[web.1]: State changed from up to crashed
2024-01-19T05:06:18.924690+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=affirmative-b9753633e8e0.herokuapp.com request_id=43bd3d20-407b-4243-a8a9-16eede4f2e27 fwd="35.2.80.155" dyno= connect= service= status=503 bytes= protocol=https
2024-01-19T05:06:19.191639+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=affirmative-b9753633e8e0.herokuapp.com request_id=7e1c4ff2-627a-4e48-80c2-1f71350613f6 fwd="35.2.80.155" dyno= connect= service= status=503 bytes= protocol=https
